# Generated by Django 4.1 on 2022-09-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_decisao_dec_motivo_decisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_resultado', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Dec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipodecisao', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
    ]
