# Generated by Django 4.1 on 2023-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_resultado_tipo_dec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_arquivo', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=30)),
                ('id_user', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
